#%RAML 0.8
---
title: raml with links 
baseUri: http://deadleg.github.io/bugs
version: v0.6

/first:
  get:
    body:
      application/json:
        schema: !include json1.json
/second:
  get:
    body:
      application/json:
        schema: !include json2.json
/third:
  get:
    body:
      application/json:
        schema: !include json3.json
